version: '2'
services:
  app:
    image: node
    restart: always
    ports: 
      - '4000:4000'
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PRISMA_URL: 'http://prisma:4466'
    depends_on:
      - prisma
    command: ['npm', 'start']

  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: postgres
            password: secret
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
